// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smartdressroom.Storage;

namespace smartdressroom.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190711215719_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("smartdressroom.Models.AdminModel", b =>
                {
                    b.Property<byte[]>("ID")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<byte[], byte[]>(v => default(byte[]), v => default(byte[]), new ConverterMappingHints(size: 16)));

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("smartdressroom.Models.ClothesModel", b =>
                {
                    b.Property<byte[]>("ID")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<byte[], byte[]>(v => default(byte[]), v => default(byte[]), new ConverterMappingHints(size: 16)));

                    b.Property<string>("Brand");

                    b.Property<int>("Code");

                    b.Property<byte[]>("CollectionID")
                        .IsRequired()
                        .HasConversion(new ValueConverter<byte[], byte[]>(v => default(byte[]), v => default(byte[]), new ConverterMappingHints(size: 16)));

                    b.Property<string>("ImgFormat");

                    b.Property<string>("ImgPath");

                    b.Property<int>("Price");

                    b.Property<string>("Size");

                    b.HasKey("ID");

                    b.HasIndex("CollectionID");

                    b.ToTable("ClothesModels");
                });

            modelBuilder.Entity("smartdressroom.Models.CollectionModel", b =>
                {
                    b.Property<byte[]>("ID")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<byte[], byte[]>(v => default(byte[]), v => default(byte[]), new ConverterMappingHints(size: 16)));

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("CollectionModels");
                });

            modelBuilder.Entity("smartdressroom.Models.ClothesModel", b =>
                {
                    b.HasOne("smartdressroom.Models.CollectionModel", "Collection")
                        .WithMany("ClothesModels")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
